name: Build APK

# Se ejecuta manualmente y también al hacer push en main.
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar el entorno e instalar dependencias necesarias
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer

      # Paso 3: Compilar la APK usando Buildozer
      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      # Paso 4: Subir el APK generado como artefacto
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: visualtagger-apk
          path: bin/*.apk
