name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar entorno
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer

      - name: Compilar APK
        run: |
          buildozer android debug

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@actions/upload-artifact@v3
        with:
          name: visualtagger-apk
          path: bin/*.apk
