name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip autoconf automake libtool pkg-config libxml2-utils libxslt1-dev
          pip install --upgrade pip
          pip install buildozer Cython

      - name: Clear Buildozer Cache
        run: rm -rf ~/.buildozer

      - name: Build APK with Buildozer
        run: buildozer android debug
